/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.edu.ister.vista;
import ec.edu.ister.vista.Aplicacion;
import java.awt.Color;
import java.awt.Dimension;
import ec.edu.ister.controlador.Conexion;
import ec.edu.ister.controlador.Coordinador;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Login extends javax.swing.JFrame {

   
    private Dimension dim;
    Coordinador coordinador;

    public Login(Coordinador coord) {
        
        initComponents();
        coordinador = coord;
        this.pack();
        dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
        //this.setUndecorated(true);
        //this.setVisible(true);
        this.getContentPane().setBackground(Color.white);

        /*Reloj r = new Reloj(lblReloj);
        Thread t2 = new Thread(r);
        t2.start();*/
//        ImageIcon imagen1 = new ImageIcon("sistemas.png");
//        Icon icono1 = new ImageIcon(imagen1.getImage().getScaledInstance(sistemas.getWidth(), sistemas.getHeight(), Image.SCALE_DEFAULT));
//        sistemas.setIcon(icono1);
//
//        ImageIcon imagen2 = new ImageIcon("electricidad.png");
//        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(electricidad.getWidth(), electricidad.getHeight(), Image.SCALE_DEFAULT));
//        electricidad.setIcon(icono2);
//
//        ImageIcon imagen3 = new ImageIcon("electronica.png");
//        Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(electronica.getWidth(), electronica.getHeight(), Image.SCALE_DEFAULT));
//        electronica.setIcon(icono3);
//
//        ImageIcon imagen4 = new ImageIcon("gastronomia.png");
//        Icon icono4 = new ImageIcon(imagen4.getImage().getScaledInstance(gastronomia.getWidth(), gastronomia.getHeight(), Image.SCALE_DEFAULT));
//        gastronomia.setIcon(icono4);
//
//        ImageIcon imagen5 = new ImageIcon("diseno.png");
//        Icon icono5 = new ImageIcon(imagen5.getImage().getScaledInstance(diseno.getWidth(), diseno.getHeight(), Image.SCALE_DEFAULT));
//        diseno.setIcon(icono5);
//
//        ImageIcon imagen6 = new ImageIcon("administracion.png");
//        Icon icono6 = new ImageIcon(imagen6.getImage().getScaledInstance(administracion.getWidth(), administracion.getHeight(), Image.SCALE_DEFAULT));
//        administracion.setIcon(icono6);
//
//        ImageIcon imagen7 = new ImageIcon("turismo.png");
//        Icon icono7 = new ImageIcon(imagen7.getImage().getScaledInstance(turismo.getWidth(), turismo.getHeight(), Image.SCALE_DEFAULT));
//        turismo.setIcon(icono7);
//
//        ImageIcon imagen8 = new ImageIcon("");//("Logo.png");
//        Icon icono8 = new ImageIcon(imagen8.getImage().getScaledInstance(Logo1.getWidth(), Logo1.getHeight(), Image.SCALE_DEFAULT));
//        Logo1.setIcon(icono8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReloj = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        sistemas = new javax.swing.JLabel();
        electronica = new javax.swing.JLabel();
        electricidad = new javax.swing.JLabel();
        gastronomia = new javax.swing.JLabel();
        turismo = new javax.swing.JLabel();
        administracion = new javax.swing.JLabel();
        diseno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboHora = new javax.swing.JComboBox<>();
        comboDia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboUsuario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblRecuperar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReloj.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(0, 153, 153));
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("RELOJ");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 370, 30));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sello.png"))); // NOI18N
        Logo1.setText(".");
        getContentPane().add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 170, 170));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("HORA: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 40, 20));

        btnSalir.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 100, 30));

        btnIngresar.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 100, 30));

        sistemas.setText(".");
        sistemas.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(sistemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 50));

        electronica.setText(".");
        electronica.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(electronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 50));

        electricidad.setText(".");
        electricidad.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(electricidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 80, 50));

        gastronomia.setText(".");
        gastronomia.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(gastronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 80, 50));

        turismo.setText(".");
        turismo.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(turismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 80, 50));

        administracion.setText(".");
        administracion.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(administracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 80, 50));

        diseno.setText(".");
        diseno.setMaximumSize(new java.awt.Dimension(60, 60));
        getContentPane().add(diseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 80, 50));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("E-mail: info@ister.edu.ec");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 330, -1));

        comboHora.setFont(new java.awt.Font("Century Schoolbook", 1, 10)); // NOI18N
        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08H:00", "09H:00", "10H:00", "11H:00", "12H:00", "13H:00" }));
        getContentPane().add(comboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, -1));

        comboDia.setFont(new java.awt.Font("Century Schoolbook", 1, 10)); // NOI18N
        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(comboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 40, 20));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DIA: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 60, 40));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Telfs: 2331-599 / 2332-554 / 2331-628");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 710, 400, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INSTITUTO TECNOLÓGICO SUPERIOR \"RUMIÑAHUI\"");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1350, 50));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tipo:");

        comboUsuario.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        comboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Docente", "Estudiante" }));
        comboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsuarioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Usuario:");

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contraseña:");

        txtUsuario.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N

        txtPass.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 153, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 370, 180));

        lblRecuperar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lblRecuperar.setForeground(new java.awt.Color(51, 51, 255));
        lblRecuperar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperar.setText("Olvido su contraseña?");
        lblRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseExited(evt);
            }
        });
        getContentPane().add(lblRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, 334, -1));

        jButton1.setText("CONECTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (comboUsuario.getSelectedItem().toString().equals("Administrador")) {
            if (txtPass.getText().equals("") && txtUsuario.getText().equals("")) {
                coordinador.hideLogin();
                coordinador.showInicio();
                coordinador.showAdministrador();
                txtPass.setText("");
                txtUsuario.setText("");
                return;
            }
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos", "Error de Acceso", JOptionPane.WARNING_MESSAGE);
        }
        
//        
//        if (comboUsuario.getSelectedItem().toString().equals("Docente")) {
//            try {
//                DocenteVo docente = coordinador.buscarDocente(txtUsuario.getText());
//                if (docente != null) {
//                    if (txtPass.getText().equals(docente.getPass())) {
//                        int dia = Integer.parseInt((String) comboDia.getSelectedItem());
//                        System.out.println(dia);
//                        int hora = 0;
//                        if (comboHora.getSelectedItem().toString().equals("08H:00")) {
//                            hora = 1;
//                        }
//                        if (comboHora.getSelectedItem().toString().equals("09H:00")) {
//                            hora = 2;
//                        }
//                        if (comboHora.getSelectedItem().toString().equals("10H:00")) {
//                            hora = 3;
//                        }
//                        if (comboHora.getSelectedItem().toString().equals("11H:00")) {
//                            hora = 4;
//                        }
//                        if (comboHora.getSelectedItem().toString().equals("12H:00")) {
//                            hora = 5;
//                        }
//                        if (comboHora.getSelectedItem().toString().equals("13H:00")) {
//                            hora = 6;
//                        }
//                        coordinador.ClaseActual(hora, dia, txtUsuario.getText());
//                        coordinador.hideLogin();
//                        coordinador.showInicioDocente();
//                        coordinador.showDocente(docente);
//                        txtPass.setText("");
//                        txtUsuario.setText("");
//                        return;
//                    }
//                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos", "Error de Acceso", JOptionPane.WARNING_MESSAGE);
//                }
//                return;
//            } catch (IOException ex) {
//                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//        if (comboUsuario.getSelectedItem().toString().equals("Estudiante")) {
//            EstudianteVo estudiante = coordinador.buscarEstudiante(txtUsuario.getText());
//            if (estudiante != null) {
//                if (txtPass.getText().equals(estudiante.getPass())) {
//                    coordinador.hideLogin();
//                    coordinador.showInicioEstudiante();
//                    coordinador.showEstudiante(estudiante);
//                    txtPass.setText("");
//                    txtUsuario.setText("");
//                    return;
//                }
//                JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos", "Error de Acceso", JOptionPane.WARNING_MESSAGE);
//            }
//        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void comboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUsuarioActionPerformed

    private void lblRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseClicked
        coordinador.hideLogin();
       // coordinador.showRecupera();
        
    }//GEN-LAST:event_lblRecuperarMouseClicked

    private void lblRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseEntered
        lblRecuperar.setForeground(Color.red);
    }//GEN-LAST:event_lblRecuperarMouseEntered

    private void lblRecuperarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseExited
        lblRecuperar.setForeground(Color.black);
    }//GEN-LAST:event_lblRecuperarMouseExited
    
      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Conexion cn = Conexion.getInstance("root","","ister");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel administracion;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboHora;
    private javax.swing.JComboBox<String> comboUsuario;
    private javax.swing.JLabel diseno;
    private javax.swing.JLabel electricidad;
    private javax.swing.JLabel electronica;
    private javax.swing.JLabel gastronomia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRecuperar;
    public javax.swing.JLabel lblReloj;
    private javax.swing.JLabel sistemas;
    private javax.swing.JLabel turismo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
